import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from '@/components/navbar'
import { CustomCursor } from '@/components/custom-cursor'
import { CursorProvider } from '@/context/cursor-context'
import { LocomotiveProvider } from '@/components/locomotive-provider'

export const metadata: Metadata = {
  title: 'Recco — Joel Cruz',
  description: 'Generated by create next app',
  icons: {
    // Public path
    icon: '/icons/favicon.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="font-abc-regular">
        <CursorProvider>
          <LocomotiveProvider>
            <Navbar />
            <CustomCursor />
            {children}
          </LocomotiveProvider>
        </CursorProvider>
      </body>
    </html>
  )
}
